---
title: "Draft R Markdown document"
author: "Your Name"
output: html_document
editor_options:
  markdown:
    wrap: 72
    canonical: true
---

```{r setup, include=FALSE}
targets::tar_config_set(
  store =
    here::here("_targets")
)
library(tidyverse)
library(tidymodels)
library(targets)
lipidomics <- targets::tar_read(lipidomics)
source(here::here("R/functions.R"))
```

## Building the model

```{r}
log_reg_specs <- logistic_reg() %>%
  set_engine("glm")
log_reg_specs
```

## Excerises

### Linear regresssion model definition

```{r}
linear_reg_specs <- linear_reg() %>%
  set_engine("lm")
linear_reg_specs
```

```{r}
lipidomics_wide <- lipidomics %>%
  mutate(metabolite = snakecase::to_snake_case(metabolite)) %>%
  pivot_wider(
    names_from = metabolite,
    values_from = value,
    values_fn = mean,
    names_prefix = "metabolite_"
  )
lipidomics_wide
```

```{r}
column_values_to_snakecase <- function(data, cols) {
  data %>%
    dplyr::mutate(dplyr::across({{ cols }}, snakecase::to_snake_case))
}

lipidomics %>%
  metabolite_values_to_snakecase()
```

```{r}

#' Convert data.frame from long to wide.
#'
#' @param data Lipidomics dataset.
#' @param values_fn Take the mean value.
#'
#' @return A data.frame in wide format
metabolites_to_wider <- function(data, values_fn) {
  data %>%
    dplyr::mutate(metabolite = snakecase::to_snake_case(metabolite)) %>%
    tidyr::pivot_wider(
      names_from = metabolite,
      values_from = value,
      values_fn = values_fn,
      names_prefix = "metabolite_"
    )
}
```

## Transforming data

```{r}
recipe_specs <- lipidomics_wide %>%
  create_recipe_spec(metabolite_cholesterol)
recipe_specs
```

```{r}

create_model_workflow(
  logistic_reg() %>% 
    set_engine("glm"),
  lipidomics_wide %>% 
    create_recipe_spec(metabolite_cholesterol)
) %>% 
  fit(lipidomics_wide) %>% 
  tidy_model_output

```
