---
# Uses Quarto metadata: https://quarto.org/docs/journals/authors.html
title: ""
author:
  - name: ""
    orcid: ""
    affiliations: 
        - name: ""
date: "`r Sys.Date()`"
format: html
---

```{r setup, include=FALSE}
library(tidyverse)
library(targets)
lipidomics <- targets::tar_read(lipidomics, 
                               store = here::here("_targets"))
```

# Abstract

Objective:

Research Design and Methods:

Results:

Conclusions:

# Introduction 

# Research Design and Methods

# Results
```{r}
targets::tar_read(df_stats_by_metabolite,
                  store = here::here("_targets")) %>% 
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r}
tar_read(fig_gender_by_class,
         store = here::here("_targets"))
```

```{r}
tar_read(fig_metabolite_distribution,
         store = here::here("_targets"))
```

# Conclusions

# Acknowledgements

# References

# Tables

# Figures

# Supplemental Material
